### ISSUE TITLE
Multi-chat instance desing

### ISSUE THREAD

**Issue by 54UL** [cBotFoundation/cBot.ts#63]
- [ ] V0.5B NPM version has to be released (#49)
- [ ] Documentation (#12)
- [ ] Other chat's platforms must be researched and implemented  (#30 #40 #39)
- [ ] Important to take into account multi treading and distribuited systems desing (#53)
